version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5070:5070
    volumes:
      - ./services/backend:/app
    command: uvicorn app.main:tank_you --reload --host 0.0.0.0 --port 5070

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'