version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5070:5070
    volumes:
      - ./services/backend:/code
    command: uvicorn main:tank_you --reload --host 0.0.0.0 --port 5070
